/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BettyRouteImport } from './routes/betty'
import { Route as KaiRouteImport } from './routes/kai'
import { Route as LunaRouteImport } from './routes/luna'
import { Route as SummerRouteImport } from './routes/summer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BettyRoute = BettyRouteImport.update({
  id: '/betty',
  path: '/betty',
  getParentRoute: () => rootRouteImport,
} as any)
const KaiRoute = KaiRouteImport.update({
  id: '/kai',
  path: '/kai',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaRoute = LunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => rootRouteImport,
} as any)
const SummerRoute = SummerRouteImport.update({
  id: '/summer',
  path: '/summer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/betty': typeof BettyRoute
  '/kai': typeof KaiRoute
  '/luna': typeof LunaRoute
  '/summer': typeof SummerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/betty': typeof BettyRoute
  '/kai': typeof KaiRoute
  '/luna': typeof LunaRoute
  '/summer': typeof SummerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/betty': typeof BettyRoute
  '/kai': typeof KaiRoute
  '/luna': typeof LunaRoute
  '/summer': typeof SummerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/betty' | '/kai' | '/luna' | '/summer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/betty' | '/kai' | '/luna' | '/summer'
  id: '__root__' | '/' | '/betty' | '/kai' | '/luna' | '/summer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BettyRoute: typeof BettyRoute
  KaiRoute: typeof KaiRoute
  LunaRoute: typeof LunaRoute
  SummerRoute: typeof SummerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betty': {
      id: '/betty'
      path: '/betty'
      fullPath: '/betty'
      preLoaderRoute: typeof BettyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kai': {
      id: '/kai'
      path: '/kai'
      fullPath: '/kai'
      preLoaderRoute: typeof KaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna': {
      id: '/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof LunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summer': {
      id: '/summer'
      path: '/summer'
      fullPath: '/summer'
      preLoaderRoute: typeof SummerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BettyRoute: BettyRoute,
  KaiRoute: KaiRoute,
  LunaRoute: LunaRoute,
  SummerRoute: SummerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
